using System;
using System.ComponentModel.DataAnnotations;

namespace ENOYAEntegrasyonV2.Models.Entities
{
    /// <summary>
    /// SEVKIYAT tablosu entity modeli
    /// ENOYAMODELLEME.sql dosyasına göre oluşturuldu
    /// </summary>
    public class SEVKIYAT
    {
        [Key]
        public decimal KOD { get; set; }
        public string? IRS_SERI_NO { get; set; }
        public string? IRS_NO { get; set; }
        public string? TARIH { get; set; }
        public string? SAAT { get; set; }
        public string? TARIHSAAT { get; set; }
        public double MIKTAR { get; set; }
        public string? OTOMATIK { get; set; }
        public string? KULLANICI { get; set; }
        public string? HAZIR_MIKTAR { get; set; }
        public string? GERI_DONEN { get; set; }
        public string? GERI_DONEN_KOD { get; set; }
        public string? RECETE_KOD { get; set; }
        public string? RECETE_INDEX { get; set; }
        public string? RECETE_AD { get; set; }
        public string? MUSTERI_KOD { get; set; }
        public string? MUSTERI_INDEX { get; set; }
        public string? MUSTERI_AD { get; set; }
        public string? SANTIYE_KOD { get; set; }
        public string? SANTIYE_AD { get; set; }
        public string? KAMYON_KOD { get; set; }
        public string? KAMYON_PLK { get; set; }
        public string? SURUCU_KOD { get; set; }
        public string? SURUCU_AD { get; set; }
        public string? HIZMET1_KOD { get; set; }
        public string? HIZMET1_AD { get; set; }
        public string? HIZMET2_KOD { get; set; }
        public string? HIZMET2_AD { get; set; }
        public string? ILAVE_SU { get; set; }
        public string? AGREGA1_IST { get; set; }
        public string? AGREGA1_TART { get; set; }
        public string? AGREGA1_VER { get; set; }
        public string? AGREGA2_IST { get; set; }
        public string? AGREGA2_TART { get; set; }
        public string? AGREGA2_VER { get; set; }
        public string? AGREGA3_IST { get; set; }
        public string? AGREGA3_TART { get; set; }
        public string? AGREGA3_VER { get; set; }
        public string? AGREGA4_IST { get; set; }
        public string? AGREGA4_TART { get; set; }
        public string? AGREGA4_VER { get; set; }
        public string? AGREGA5_IST { get; set; }
        public string? AGREGA5_TART { get; set; }
        public string? AGREGA5_VER { get; set; }
        public string? AGREGA6_IST { get; set; }
        public string? AGREGA6_TART { get; set; }
        public string? AGREGA6_VER { get; set; }
        public string? CIMENTO1_IST { get; set; }
        public string? CIMENTO1_VER { get; set; }
        public string? CIMENTO2_IST { get; set; }
        public string? CIMENTO2_VER { get; set; }
        public string? CIMENTO3_IST { get; set; }
        public string? CIMENTO3_VER { get; set; }
        public string? CIMENTO4_IST { get; set; }
        public string? CIMENTO4_VER { get; set; }
        public string? SU1_IST { get; set; }
        public string? SU1_TART { get; set; }
        public string? SU1_VER { get; set; }
        public string? SU2_IST { get; set; }
        public string? SU2_TART { get; set; }
        public string? SU2_VER { get; set; }
        public string? KATKI1_IST { get; set; }
        public string? KATKI1_VER { get; set; }
        public string? KATKI2_IST { get; set; }
        public string? KATKI2_VER { get; set; }
        public string? KATKI3_IST { get; set; }
        public string? KATKI3_VER { get; set; }
        public string? KATKI4_IST { get; set; }
        public string? KATKI4_VER { get; set; }
        public string? AG1SILOAD { get; set; }
        public string? AG2SILOAD { get; set; }
        public string? AG3SILOAD { get; set; }
        public string? AG4SILOAD { get; set; }
        public string? AG5SILOAD { get; set; }
        public string? AG6SILOAD { get; set; }
        public string? CM1SILOAD { get; set; }
        public string? CM2SILOAD { get; set; }
        public string? CM3SILOAD { get; set; }
        public string? CM4SILOAD { get; set; }
        public string? SU1SILOAD { get; set; }
        public string? SU2SILOAD { get; set; }
        public string? KT1SILOAD { get; set; }
        public string? KT2SILOAD { get; set; }
        public string? KT3SILOAD { get; set; }
        public string? KT4SILOAD { get; set; }
        public string? AKMHTVAR { get; set; }
        public string? GECHTVAR { get; set; }
        public string? TESLIMONAY { get; set; }
        public string? GKYOGSET { get; set; }
        public string? OZGAGR { get; set; }
        public string? KUMNEM { get; set; }
        public string? KUMGKNEM { get; set; }
        public string? KAMREV { get; set; }
        public string? HZMAG1_VER { get; set; }
        public string? HZMAG2_VER { get; set; }
        public string? HZMAG3_VER { get; set; }
        public string? HZMAG4_VER { get; set; }
        public string? HZMAG5_VER { get; set; }
        public string? HZMAG6_VER { get; set; }
        public string? HZMCM1_VER { get; set; }
        public string? HZMCM2_VER { get; set; }
        public string? HZMCM3_VER { get; set; }
        public string? HZMCM4_VER { get; set; }
        public string? HZMSU1_VER { get; set; }
        public string? HZMSU2_VER { get; set; }
        public string? HZMKT1_VER { get; set; }
        public string? HZMKT2_VER { get; set; }
        public string? HZMKT3_VER { get; set; }
        public string? HZMKT4_VER { get; set; }
        public string? HZMREC_AD { get; set; }
        public string? HZMREC_INDEX { get; set; }
        public string? HZMREC_KOD { get; set; }
        public string? AG1_BRM { get; set; }
        public string? AG2_BRM { get; set; }
        public string? AG3_BRM { get; set; }
        public string? AG4_BRM { get; set; }
        public string? AG5_BRM { get; set; }
        public string? AG6_BRM { get; set; }
        public string? CM1_BRM { get; set; }
        public string? CM2_BRM { get; set; }
        public string? CM3_BRM { get; set; }
        public string? CM4_BRM { get; set; }
        public string? SU1_BRM { get; set; }
        public string? SU2_BRM { get; set; }
        public string? KT1_BRM { get; set; }
        public string? KT2_BRM { get; set; }
        public string? KT3_BRM { get; set; }
        public string? KT4_BRM { get; set; }
        public string? SIP_KOD { get; set; }
        public string? AG1NEMORT { get; set; }
        public string? AG2NEMORT { get; set; }
        public string? AG3NEMORT { get; set; }
        public string? AG4NEMORT { get; set; }
        public string? AG5NEMORT { get; set; }
        public string? AG6NEMORT { get; set; }
        public string? AG1GKORT { get; set; }
        public string? AG2GKORT { get; set; }
        public string? AG3GKORT { get; set; }
        public string? AG4GKORT { get; set; }
        public string? AG5GKORT { get; set; }
        public string? AG6GKORT { get; set; }
        public string? AG1NEMSUTOP { get; set; }
        public string? AG2NEMSUTOP { get; set; }
        public string? AG3NEMSUTOP { get; set; }
        public string? AG4NEMSUTOP { get; set; }
        public string? AG5NEMSUTOP { get; set; }
        public string? AG6NEMSUTOP { get; set; }
        public string? AG1GKSUTOP { get; set; }
        public string? AG2GKSUTOP { get; set; }
        public string? AG3GKSUTOP { get; set; }
        public string? AG4GKSUTOP { get; set; }
        public string? AG5GKSUTOP { get; set; }
        public string? AG6GKSUTOP { get; set; }
        public string? AGMANHT { get; set; }
        public string? CMMANHT { get; set; }
        public string? SUMANHT { get; set; }
        public string? KTMANHT { get; set; }
        public string? URTSURE { get; set; }
        public string? MIXCAP { get; set; }
        public string? KARSUR { get; set; }
        public string? URTSUCIM { get; set; }
        public string? URTSUCIMKAT { get; set; }
        public string? ORDER_NO { get; set; }
        public string? RELEASE_NO { get; set; }
        public string? SEQUENCE_NO { get; set; }
        public string? ORDER_CODE { get; set; }
        public string? START_TIME { get; set; }
        public string? FINISH_TIME { get; set; }
        public string? RESET_INFO { get; set; }
        public string? HURDA_INFO { get; set; }
        public string? DURUM { get; set; }
        public string? TOLHATADURUM { get; set; }
        public string? URTBIRDURUM { get; set; }
        public string? ILAVE_KT1 { get; set; }
        public string? ILAVE_KT2 { get; set; }
        public string? ILAVE_KT3 { get; set; }
        public string? ILAVE_KT4 { get; set; }

    }
}

